###
POST http://localhost:2001/api/v1/users
Content-Type: application/json

{
    "username":"ichsan",
    "email":"ichsan@gmail.com",
    "password":"iniuserichsan"
}

###
GET http://localhost:2001/api/v1/users/

### 
GET http://localhost:2001/api/v1/users/1


###
DELETE http://localhost:2001/api/v1/users/1

###
PUT http://localhost:2001/api/v1/users/1